import { module2_3_1, module2_3_2 } from "../../utils/images";

const Module2_3 = ({ currentModule }) => {
  return (
    <div id="submodule-content-2.3" className="bg-white p-8 rounded-lg">
      {/* === Submodule Heading === */}
      <h2 className="text-2xl font-bold text-blue-600 pb-2 border-b  inline-block mb-8">
        Activity 1: Advanced Summarization
      </h2>

      {/* === Introduction Text === */}
      <p className="text-lg text-gray-700 leading-relaxed mb-8">
        Having learned about AI’s capabilities in conducting research and summarizing text, let's attempt an activity to test your understanding.
      </p>

      <h3 className="text-xl font-semibold text-gray-800 mb-4">Scenario</h3>
      <p className="text-gray-700 mb-6 leading-relaxed">
        You have received a 15-page research paper, <strong>"Unleashing digital transformation to achieve the sustainable development goals."</strong> 
        Your goal is to create a one-page summary highlighting only the key digital technologies, sustainable business practices, and actions required:
      </p>

      <ul className="list-disc pl-6 space-y-2 mb-6 text-gray-700">
        <li>Digital technologies for SDGs</li>
        <li>Sustainable Business Practices</li>
        <li>Gaps and future directions</li>
      </ul>

      <h3 className="text-xl font-semibold text-gray-800 mb-4">Goal</h3>
      <p className="text-gray-700 mb-8 leading-relaxed">
        Use <strong>Productivity GPT</strong> to generate a 1-page summary of the 15-page-long research paper, 
        <strong>"Unleashing digital transformation to achieve the sustainable development goals across multiple sectors."</strong>
      </p>

      <p className="text-gray-700 mb-12 leading-relaxed">
        You must have seen Productivity GPT right as you got started with this segment. Missed it? 
        Just scroll to the top of this page, and you will find this amazing little tool right below the header bar. 
        Simply click on the icon and start exploring its immense possibilities!
      </p>

      {/* === First Image === */}
      <div className="flex justify-center mb-8">
        <div className="w-full sm:w-3/4 md:w-2/3 lg:w-1/2 rounded-lg overflow-hidden">
          <img
            src={module2_3_1}
            alt="Activity illustration 1"
            className="w-full h-auto object-contain"
          />
        </div>
      </div>

      {/* === Second Image === */}
      <div className="flex justify-center mb-10">
        <div className="w-full sm:w-3/4 md:w-2/3 lg:w-1/2 rounded-lg overflow-hidden">
          <img
            src={module2_3_2}
            alt="Activity illustration 2"
            className="w-full h-auto object-contain"
          />
        </div>
      </div>

      {/* === Follow-up Steps === */}
      <h3 className="text-xl font-semibold text-black pb-2  inline-block mb-6">
        Please Follow The Steps Given Below:
      </h3>

      {/* === Step 1 === */}
      <h4 className="text-xl font-semibold text-gray-800 mb-2">Step 1: Upload the Policy</h4>
      <ol className="list-decimal pl-6 space-y-2 mb-6 text-gray-700">
        <li>Go to Productivity GPT on the platform.</li>
        <li>Upload (or paste the text from) the policy document by downloading it from here.</li>
      </ol>

      {/* === Step 2 === */}
      <h4 className="text-xl font-semibold text-gray-800 mb-2">Step 2: Generate a First Draft</h4>
      <ol className="list-decimal pl-6 space-y-2 mb-6 text-gray-700">
        <li>
          Prompt Productivity GPT for a rough summary, for example:  
          <br />
          <code className="block bg-gray-100 p-3 rounded-lg mt-2">
            "Summarize this 15-page report on Unleashing Digital Transformation to Achieve the Sustainable Development Goals in one page. 
            Focus on key elements such as the current landscape, major sectoral and technological challenges identified, 
            key areas of adoption, and the most urgent actions recommended."
          </code>
        </li>
        <li>Copy and paste this prompt into Productivity GPT to generate the first summary draft.</li>
        <li>Review the first draft output generated by the AI.</li>
      </ol>

      {/* === Step 3 === */}
      <h4 className="text-xl font-semibold text-gray-800 mb-2">Step 3: Iterative Summarization</h4>
      <ol className="list-decimal pl-6 space-y-2 mb-6 text-gray-700">
        <li>
          If the first draft is too lengthy or unclear, refine it:
          <ul className="list-disc pl-6 space-y-1 mt-2">
            <li>
              To shorten:  
              <code className="block bg-gray-100 p-2 rounded-lg mt-1">
                "Condense the summary to ~200 words, emphasizing the key gaps, areas of progress, and immediate next steps."
              </code>
            </li>
            <li>
              To improve clarity:  
              <code className="block bg-gray-100 p-2 rounded-lg mt-1">
                "Simplify complex sections for better understanding and readability while maintaining the core information."
              </code>
            </li>
          </ul>
        </li>
        <li>
          Still not satisfied? Try:  
          <code className="block bg-gray-100 p-2 rounded-lg mt-1">
            "Give the summary in bullet points. Retain the most critical technologies like AI, big data, and cloud computing."
          </code>
        </li>
      </ol>

      {/* === Step 4 === */}
      <h4 className="text-xl font-semibold text-gray-800 mb-2">Step 4: Prompt Chaining</h4>
      <ol className="list-decimal pl-6 space-y-2 mb-6 text-gray-700">
        <li>
          For deeper sections, use sub-prompts:  
          <code className="block bg-gray-100 p-2 rounded-lg mt-1">
            "Highlight the key takeaways of the digital technologies being leveraged across different sectors and industries."
          </code>
        </li>
        <li>
          For simplifying complex ideas:  
          <code className="block bg-gray-100 p-2 rounded-lg mt-1">
            "Explain the key talking points of the scope for future research in 2-3 sentences for clarity and then reinsert it into the 200-word summary."
          </code>
        </li>
      </ol>

      <p className="text-gray-700 leading-relaxed">
        You can iterate further and create the perfect summary as per your requirements!
      </p>

      <p className="text-gray-700 leading-relaxed mt-4">
        <strong>Note:</strong> Here's another document for you to practice on; this one is specific to the education sector. 
        Remember to modify your prompt for the details of this document!
      </p>
    </div>
  );
};

export default Module2_3;
